# -*- coding: utf-8 -*-
"""finbertvsroberta_training_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQ7nFodk3omsIDPmEPQeZiqU0orhL4fq
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q transformers pandas numpy torch

import os, gc, numpy as np, pandas as pd, torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TextClassificationPipeline

print("CUDA available:", torch.cuda.is_available())
device = 0 if torch.cuda.is_available() else -1  # GPU w Colabie = 0, inaczej CPU

# <<< PODAJ NAZWĘ PLIKU >>>
CSV_PATH = "/content/drive/MyDrive/Thesis_v2/tweet_impact_dataset_merged.csv"

df = pd.read_csv(CSV_PATH)
print("Kolumny:", list(df.columns))
assert "tweet_id" in df.columns, "Brak kolumny 'tweet_id'."
# wykryj kolumnę z tekstem
TEXT_COL = "text" if "text" in df.columns else ("tweet" if "tweet" in df.columns else None)
assert TEXT_COL is not None, "Brak kolumny 'text' lub 'tweet'."

# usuń duplikaty i puste teksty
n0 = len(df)
df = df.drop_duplicates(subset=["tweet_id"]).copy()
df = df[df[TEXT_COL].astype(str).str.strip().ne("")].copy()
print(f"Usunięto duplikaty/puste: {n0-len(df)} | Pozostało: {len(df)} wierszy")

df.head(2)

import re

def clean_tweet(s: str) -> str:
    s = re.sub(r"http\S+", "http://url", s)      # linki → placeholder
    s = re.sub(r"@\w+", "@user", s)              # wzmianki → @user
    s = re.sub(r"\s+", " ", s).strip()
    return s

# Połącz kolumny text i quote, jeśli isQuote jest True
# Sprawdź, czy kolumna 'quote' istnieje i nie jest pusta (zawiera słowniki)
if 'quote' in df.columns and df['isQuote'].any():
    # Użyj apply do warunkowego łączenia tekstów
    # Zadbaj o to, aby quote było stringiem i nie było NaN
    df['combined_text'] = df.apply(
        lambda row: f"{row[TEXT_COL]} [QUOTE] {row['quote']}" if row['isQuote'] and pd.notna(row['quote']) else row[TEXT_COL],
        axis=1
    )
    texts = df['combined_text'].astype(str).map(clean_tweet).tolist()
    print("Połączono kolumny 'text' i 'quote' dla tweetów z 'isQuote=1'.")
else:
    texts = df[TEXT_COL].astype(str).map(clean_tweet).tolist()
    print("Kolumna 'quote' nie istnieje lub brak tweetów z 'isQuote=1'. Analizuję tylko kolumnę 'text'.")


df.head(5)



def run_model(ckpt: str, texts, prefix: str, batch_size: int = 64) -> pd.DataFrame:
    tok = AutoTokenizer.from_pretrained(ckpt, use_fast=True)
    mod = AutoModelForSequenceClassification.from_pretrained(ckpt)
    pipe = TextClassificationPipeline(
        model=mod, tokenizer=tok, device=device, truncation=True, max_length=128
    )
    # pełny rozkład dla każdej próbki
    out = pipe(texts, batch_size=batch_size, return_all_scores=True)

    def norm_label(name: str) -> str:
        n = name.lower().replace("label_", "")
        if n.startswith("neg"): return "negative"
        if n.startswith("neu"): return "neutral"
        if n.startswith("pos"): return "positive"
        # dla modeli z LABEL_0/1/2 spróbuj mapować po id2label
        if n in {"0","1","2"}:  # awaryjnie: typowa kolejność CardiffNLP: neg, neu, pos
            return {"0":"negative","1":"neutral","2":"positive"}[n]
        return n

    rows, labels, maxprobs = [], [], []
    for row in out:
        d = {norm_label(s["label"]): float(s["score"]) for s in row}
        pneg = d.get("negative", 0.0); pneu = d.get("neutral", 0.0); ppos = d.get("positive", 0.0)
        rows.append([pneg, pneu, ppos])
        arr = np.array([pneg, pneu, ppos]); labels.append(["negative","neutral","positive"][arr.argmax()])
        maxprobs.append(float(arr.max()))
    res = pd.DataFrame(rows, columns=[f"{prefix}_p_negative", f"{prefix}_p_neutral", f"{prefix}_p_positive"])
    res[f"{prefix}_label"] = labels
    res[f"{prefix}_maxprob"] = maxprobs
    return res



# FinBERT — domena finansowa
fb_df = run_model("ProsusAI/finbert", texts, "fb", batch_size=64)
# Twitter-RoBERTa — domena tweetowa
tw_df = run_model("cardiffnlp/twitter-roberta-base-sentiment-latest", texts, "tw", batch_size=64)

sent = pd.concat([fb_df, tw_df], axis=1)
sent.head(3)

def ensemble_row(r):
    # większość z dwóch: jeśli remis, wybierz label z wyższą maxprob
    if r["fb_label"] == r["tw_label"]:
        label = r["fb_label"]
    else:
        label = r["fb_label"] if r["fb_maxprob"] >= r["tw_maxprob"] else r["tw_label"]
    conf = max(r["fb_maxprob"], r["tw_maxprob"])
    return pd.Series({"ens_label": label, "ens_conf": conf})

ens = sent.apply(ensemble_row, axis=1)
sent = pd.concat([sent, ens], axis=1)
sent["low_conf"] = (sent["ens_conf"] < 0.60).astype(int)  # próg możesz zmienić później

# dołącz do oryginalnego df po indexie (kolejność nie zmieniana)
out = pd.concat([df.reset_index(drop=True), sent.reset_index(drop=True)], axis=1)
out.head(3)

print("Rozkład klas FinBERT:\n", out["fb_label"].value_counts(normalize=True).round(3))
print("\nRozkład klas Twitter-RoBERTa:\n", out["tw_label"].value_counts(normalize=True).round(3))
print("\nRozkład klas ENSEMBLE:\n", out["ens_label"].value_counts(normalize=True).round(3))

agree = (out["fb_label"] == out["tw_label"]).mean()
print(f"\nZgodność fb vs tw: {agree:.3f}")

print("\nPrzykładowe high-confidence pozytywne:")
display(out[(out["ens_label"]=="positive") & (out["ens_conf"]>=0.85)][[TEXT_COL,"ens_label","ens_conf"]].head(5))

print("\nPrzykładowe high-confidence negatywne:")
display(out[(out["ens_label"]=="negative") & (out["ens_conf"]>=0.85)][[TEXT_COL,"ens_label","ens_conf"]].head(5))

OUT_PATH = CSV_PATH.replace(".csv", "_with_sentiment.csv")
out.to_csv(OUT_PATH, index=False)
print("Zapisano:", OUT_PATH)

# sprzątanie pamięci (opcjonalnie)
del fb_df, tw_df, sent; gc.collect()

out.head(3)





import pandas as pd, numpy as np
import matplotlib.pyplot as plt
import os, datetime as dt

# <<< podaj nazwę pliku wygenerowanego wcześniej >>>
PATH = "/content/drive/MyDrive/Thesis_v2/tweet_impact_dataset_with_sentiment.csv"

df = pd.read_csv(PATH)
assert {"fb_label","fb_p_negative","fb_p_neutral","fb_p_positive",
        "tw_label","tw_p_negative","tw_p_neutral","tw_p_positive",
        "ens_label","ens_conf"}.issubset(df.columns), "Brak wymaganych kolumn z sentymentem."

LABELS = ["negative","neutral","positive"]

outdir = "fig_sentiment"
os.makedirs(outdir, exist_ok=True)
timestamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
print("Wierszy:", len(df))

def dist(series):
    c = series.value_counts().reindex(LABELS, fill_value=0)
    p = (c / c.sum()).round(3)
    return c, p

fb_c, fb_p = dist(df["fb_label"])
tw_c, tw_p = dist(df["tw_label"])
en_c, en_p = dist(df["ens_label"])

agree = (df["fb_label"] == df["tw_label"]).mean()

print("=== Rozkład FinBERT ===\nliczby:\n", fb_c, "\nproporcje:\n", fb_p, "\n")
print("=== Rozkład Twitter-RoBERTa ===\nliczby:\n", tw_c, "\nproporcje:\n", tw_p, "\n")
print("=== Rozkład Ensemble ===\nliczby:\n", en_c, "\nproporcje:\n", en_p, "\n")
print(f"Zgodność fb vs tw (procent tych samych etykiet): {agree:.3f}")

# udział tweetów high-confidence wg progu
for thr in [0.6, 0.7, 0.8, 0.9]:
    share = (df["ens_conf"] >= thr).mean()
    print(f"Udział high-confidence (ens_conf ≥ {thr}): {share:.3f}")

def plot_bar(proportions, title, fname):
    plt.figure(figsize=(5,4))
    vals = [proportions.get(x,0) for x in LABELS]
    plt.bar(LABELS, vals)
    plt.ylim(0, 1)
    plt.ylabel("Udział")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, f"{timestamp}_{fname}.png"), dpi=150)
    plt.show()

plot_bar(fb_p, "Rozkład klas – FinBERT", "dist_finbert")
plot_bar(tw_p, "Rozkład klas – Twitter-RoBERTa", "dist_twitter_roberta")
plot_bar(en_p, "Rozkład klas – Ensemble", "dist_ensemble")

import numpy as np

ct = pd.crosstab(df["fb_label"], df["tw_label"]).reindex(index=LABELS, columns=LABELS, fill_value=0)
ct_norm = (ct / ct.values.sum()).round(3)  # normalizacja globalna (udział całości)

def plot_heatmap(mat, title, fname):
    plt.figure(figsize=(5,4))
    im = plt.imshow(mat.values, aspect='auto')
    plt.xticks(range(len(LABELS)), LABELS)
    plt.yticks(range(len(LABELS)), LABELS)
    plt.xlabel("Twitter-RoBERTa")
    plt.ylabel("FinBERT")
    plt.title(title)
    # adnotacje
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            txt = str(mat.values[i,j])
            plt.text(j, i, txt, ha='center', va='center')
    plt.colorbar(im, fraction=0.046, pad=0.04)
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, f"{timestamp}_{fname}.png"), dpi=150)
    plt.show()

plot_heatmap(ct, "Zgodność etykiet (liczby)", "agree_counts")
plot_heatmap(ct_norm, "Zgodność etykiet (udzial całkowity)", "agree_shares")

# jeśli nie masz fb_maxprob/tw_maxprob, policz je z kolumn p_*
if "fb_maxprob" not in df.columns:
    df["fb_maxprob"] = df[["fb_p_negative","fb_p_neutral","fb_p_positive"]].max(axis=1)
if "tw_maxprob" not in df.columns:
    df["tw_maxprob"] = df[["tw_p_negative","tw_p_neutral","tw_p_positive"]].max(axis=1)

def plot_hist(series, title, fname, bins=20):
    plt.figure(figsize=(5,4))
    plt.hist(series.dropna().values, bins=bins)
    plt.xlabel("Pewność (max probability)")
    plt.ylabel("Liczba tweetów")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, f"{timestamp}_{fname}.png"), dpi=150)
    plt.show()

plot_hist(df["fb_maxprob"], "Pewność predykcji – FinBERT", "hist_conf_finbert")
plot_hist(df["tw_maxprob"], "Pewność predykcji – Twitter-RoBERTa", "hist_conf_twitter")
plot_hist(df["ens_conf"],   "Pewność predykcji – Ensemble", "hist_conf_ensemble")

# jeśli nie masz fb_maxprob/tw_maxprob, policz je z kolumn p_*
if "fb_maxprob" not in df.columns:
    df["fb_maxprob"] = df[["fb_p_negative","fb_p_neutral","fb_p_positive"]].max(axis=1)
if "tw_maxprob" not in df.columns:
    df["tw_maxprob"] = df[["tw_p_negative","tw_p_neutral","tw_p_positive"]].max(axis=1)

def plot_hist(series, title, fname, bins=20):
    plt.figure(figsize=(5,4))
    plt.hist(series.dropna().values, bins=bins)
    plt.xlabel("Pewność (max probability)")
    plt.ylabel("Liczba tweetów")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, f"{timestamp}_{fname}.png"), dpi=150)
    plt.show()

plot_hist(df["fb_maxprob"], "Pewność predykcji – FinBERT", "hist_conf_finbert")
plot_hist(df["tw_maxprob"], "Pewność predykcji – Twitter-RoBERTa", "hist_conf_twitter")
plot_hist(df["ens_conf"],   "Pewność predykcji – Ensemble", "hist_conf_ensemble")

df["fb_pdiff"] = df["fb_p_positive"] - df["fb_p_negative"]
df["tw_pdiff"] = df["tw_p_positive"] - df["tw_p_negative"]

def plot_hist_pdiff(series, title, fname, bins=30):
    plt.figure(figsize=(5,4))
    plt.hist(series.dropna().values, bins=bins)
    plt.xlabel("p(positive) − p(negative)")
    plt.ylabel("Liczba tweetów")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, f"{timestamp}_{fname}.png"), dpi=150)
    plt.show()

plot_hist_pdiff(df["fb_pdiff"], "Siła polaryzacji – FinBERT", "pdiff_finbert")
plot_hist_pdiff(df["tw_pdiff"], "Siła polaryzacji – Twitter-RoBERTa", "pdiff_twitter")

sample = df.sample(n=min(len(df), 5000), random_state=42)  # ogranicz punkty, by było czytelnie

plt.figure(figsize=(5,4))
plt.scatter(sample["fb_p_positive"], sample["tw_p_positive"], alpha=0.5, s=10)
plt.xlabel("FinBERT: p_positive")
plt.ylabel("Twitter-RoBERTa: p_positive")
plt.title("Korelacja p_positive (FinBERT vs Twitter-RoBERTa)")
plt.tight_layout()
plt.savefig(os.path.join(outdir, f"{timestamp}_scatter_p_pos_fb_vs_tw.png"), dpi=150)
plt.show()

corr = df["fb_p_positive"].corr(df["tw_p_positive"])
print(f"Korelacja Pearsona p_positive (fb vs tw): {corr:.3f}")

summary = pd.DataFrame({
    "model":["FinBERT","Twitter-RoBERTa","Ensemble"],
    "neg":[fb_p["negative"], tw_p["negative"], en_p["negative"]],
    "neu":[fb_p["neutral"], tw_p["neutral"], en_p["neutral"]],
    "pos":[fb_p["positive"], tw_p["positive"], en_p["positive"]],
})

summary_path = os.path.join(outdir, f"{timestamp}_summary_distributions.csv")
summary.to_csv(summary_path, index=False)
print("Zapisano tabelę rozkładów:", summary_path)

agree_table = pd.crosstab(df["fb_label"], df["tw_label"]).reindex(index=LABELS, columns=LABELS, fill_value=0)
agree_path = os.path.join(outdir, f"{timestamp}_fb_vs_tw_crosstab.csv")
agree_table.to_csv(agree_path)
print("Zapisano macierz zgodności:", agree_path)



import pandas as pd
import os

LLM_PATH = "/content/drive/MyDrive/THESIS/combined_top_with_llm_final.parquet"

if not os.path.exists(LLM_PATH):
    print(f"Error: The file '{LLM_PATH}' does not exist. Please ensure the file is present at this path and verify the filename.")
    llm_df = pd.DataFrame() # Create an empty DataFrame to avoid errors in subsequent steps
else:
    llm_df = pd.read_parquet(LLM_PATH)


print("LLM DataFrame head:")
print(llm_df.head(1000))

print(llm_df.columns.tolist())

import pandas as pd
import os

LLM_PATH = "/content/drive/MyDrive/THESIS/combined_top_with_llm_final.parquet"

llm_df = pd.read_parquet(LLM_PATH)
if 'llm_sent_tweet' in llm_df.columns and 'tweet_id' in llm_df.columns:
      llm_df = llm_df[['clean_text', 'combined_quote_info', 'isRetweet', 'year','month', 'llm_sent_tweet','llm_conf']].copy()
      print("LLM sentiment data loaded and prepared successfully.")
else:
     print("Error: Required columns ('tweet_id' or 'llm_sent_tweet') not found in LLM DataFrame.")
     llm_df = pd.DataFrame() # Initialize as empty if columns are missing

print("LLM DataFrame head:")
print(llm_df.head())

!pip install -q transformers accelerate

import numpy as np
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

# 1. Tekst, na którym będziemy liczyć sentyment
#    - jeśli to retweet i jest combined_quote_info -> użyj głównie cytowanego tweeta
#    - w pozostałych przypadkach: clean_text + (ewentualnie) combined_quote_info jako kontekst
def build_sent_text(row):
    base = ""
    if pd.notna(row.get("clean_text")):
        base = str(row["clean_text"]).strip()

    quote = ""
    if "combined_quote_info" in row and pd.notna(row["combined_quote_info"]):
        quote = str(row["combined_quote_info"]).strip()

    # jeśli to retweet i mamy cytowaną treść, traktuj cytat jako główny tekst
    if row.get("isRetweet", 0) == 1 and quote:
        text = quote
    else:
        text = base
        if quote:
            text = (text + " " + quote).strip()

    return text

llm_df["sent_text"] = llm_df.apply(build_sent_text, axis=1)

# maska na niepuste teksty, żeby nie puszczać pustych stringów przez modele
non_empty_mask = llm_df["sent_text"].str.strip().ne("")
texts = llm_df.loc[non_empty_mask, "sent_text"].tolist()

print(f"Liczba tweetów do analizy sentymentu: {len(texts)}")

# 2. Modele: FinBERT + RoBERTa (twitterowa)
device = 0 if torch.cuda.is_available() else -1

finbert_name = "ProsusAI/finbert"
roberta_name = "cardiffnlp/twitter-roberta-base-sentiment-latest"

finbert = pipeline(
    "text-classification",
    model=finbert_name,
    tokenizer=finbert_name,
    device=device,
    truncation=True,
    max_length=128 # Explicitly set max_length
)

roberta = pipeline(
    "text-classification",
    model=roberta_name,
    tokenizer=roberta_name,
    device=device,
    truncation=True,
    max_length=128 # Explicitly set max_length to avoid tensor size mismatch
)

# 3. Funkcja do batchowego odpalania pipeline
def run_pipe(pipe, texts, batch_size=32):
    labels, scores = [], []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]
        outputs = pipe(batch)
        for out in outputs:
            # normalizujemy label do małych liter, żeby łatwo porównać z llm_sent_tweet
            labels.append(out["label"].lower())
            scores.append(float(out["score"]))
    return labels, scores

# 4. Liczymy sentymenty
fin_labels, fin_scores = run_pipe(finbert, texts)
rob_labels, rob_scores = run_pipe(roberta, texts)

# 5. Wrzucamy z powrotem do DataFrame (NaN dla pustych tekstów)
llm_df["fin_sent_tweet"] = np.nan
llm_df["fin_conf"] = np.nan
llm_df["rob_sent_tweet"] = np.nan
llm_df["rob_conf"] = np.nan

llm_df.loc[non_empty_mask, "fin_sent_tweet"] = fin_labels
llm_df.loc[non_empty_mask, "fin_conf"] = fin_scores
llm_df.loc[non_empty_mask, "rob_sent_tweet"] = rob_labels
llm_df.loc[non_empty_mask, "rob_conf"] = rob_scores

print(llm_df[["clean_text", "sent_text", "llm_sent_tweet",
              "fin_sent_tweet", "rob_sent_tweet"]].head())

import pandas as pd
import matplotlib.pyplot as plt

# Upewniamy się, że sentymenty są typu tekstowego (żeby nie było ostrzeżeń pandas)
for col in ["llm_sent_tweet", "fin_sent_tweet", "rob_sent_tweet"]:
    if col in llm_df.columns:
        llm_df[col] = llm_df[col].astype("string")

# Bierzemy tylko wiersze, gdzie wszystkie trzy modele mają etykietę
cols = ["llm_sent_tweet", "fin_sent_tweet", "rob_sent_tweet"]
sent_df = llm_df.dropna(subset=cols).copy()

print(f"Liczba tweetów z oceną wszystkich trzech modeli: {len(sent_df)}")

# 1. Rozkład klas dla każdego modelu (procentowo + wykres słupkowy)
model_names = {
    "llm_sent_tweet": "LLM",
    "fin_sent_tweet": "FinBERT",
    "rob_sent_tweet": "RoBERTa"
}

for col in cols:
    print(f"\nRozkład klas dla {model_names[col]} (w %):")
    dist = (sent_df[col].value_counts(normalize=True) * 100).round(2)
    print(dist)

    # wykres rozkładu
    plt.figure()
    dist.sort_index().plot(kind="bar")
    plt.title(f"Rozkład sentymentu – {model_names[col]}")
    plt.xlabel("Klasa")
    plt.ylabel("Procent tweetów")
    plt.xticks(rotation=0)
    plt.tight_layout()
    plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Upewniamy się, że sentymenty są typu tekstowego (żeby nie było ostrzeżeń pandas)
for col in ["llm_sent_tweet", "fin_sent_tweet", "rob_sent_tweet"]:
    if col in llm_df.columns:
        llm_df[col] = llm_df[col].astype("string")

# Bierzemy tylko wiersze, gdzie wszystkie trzy modele mają etykietę
cols = ["llm_sent_tweet", "fin_sent_tweet", "rob_sent_tweet"]
sent_df = llm_df.dropna(subset=cols).copy()

print(f"Liczba tweetów z oceną wszystkich trzech modeli: {len(sent_df)}")

# 1. Rozkład klas dla każdego modelu (procentowo + wykres słupkowy)
model_names = {
    "llm_sent_tweet": "LLM",
    "fin_sent_tweet": "FinBERT",
    "rob_sent_tweet": "RoBERTa"
}

for col in cols:
    print(f"\nRozkład klas dla {model_names[col]} (w %):")
    dist = (sent_df[col].value_counts(normalize=True) * 100).round(2)
    print(dist)

    # wykres rozkładu
    plt.figure()
    dist.sort_index().plot(kind="bar")
    plt.title(f"Rozkład sentymentu – {model_names[col]}")
    plt.xlabel("Klasa")
    plt.ylabel("Procent tweetów")
    plt.xticks(rotation=0)
    plt.tight_layout()
    plt.show()

# 2. Zgodność między modelami (procent tweetów, gdzie etykiety są takie same)
sent_df["agree_llm_fin"] = sent_df["llm_sent_tweet"] == sent_df["fin_sent_tweet"]
sent_df["agree_llm_rob"] = sent_df["llm_sent_tweet"] == sent_df["rob_sent_tweet"]
sent_df["agree_fin_rob"] = sent_df["fin_sent_tweet"] == sent_df["rob_sent_tweet"]
sent_df["agree_all"] = (
    (sent_df["llm_sent_tweet"] == sent_df["fin_sent_tweet"]) &
    (sent_df["llm_sent_tweet"] == sent_df["rob_sent_tweet"])
)

def pct(series):
    return round(series.mean() * 100, 2)

print("\nProcent zgodności etykiet:")
print(f"LLM vs FinBERT:  {pct(sent_df['agree_llm_fin'])} %")
print(f"LLM vs RoBERTa:  {pct(sent_df['agree_llm_rob'])} %")
print(f"FinBERT vs RoBERTa: {pct(sent_df['agree_fin_rob'])} %")
print(f"Wszyscy trzej zgodni: {pct(sent_df['agree_all'])} %")

# 3. Kategorie „kto z kim się zgadza” (rozłączne), do prostego porównania podobieństwa
only_llm_fin = sent_df["agree_llm_fin"] & ~sent_df["agree_all"]
only_llm_rob = sent_df["agree_llm_rob"] & ~sent_df["agree_all"]
only_fin_rob = sent_df["agree_fin_rob"] & ~sent_df["agree_all"]
none_agree   = ~(sent_df["agree_llm_fin"] | sent_df["agree_llm_rob"] | sent_df["agree_fin_rob"])

agreement_counts = pd.Series({
    "wszyscy trzej": sent_df["agree_all"].sum(),
    "tylko LLM–FinBERT": only_llm_fin.sum(),
    "tylko LLM–RoBERTa": only_llm_rob.sum(),
    "tylko FinBERT–RoBERTa": only_fin_rob.sum(),
    "brak zgodności": none_agree.sum()
})

agreement_percent = (agreement_counts / len(sent_df) * 100).round(2)

print("\nRozkład typów zgodności (liczby):")
print(agreement_counts)
print("\nRozkład typów zgodności (w %):")
print(agreement_percent)

plt.figure()
agreement_percent.plot(kind="bar")
plt.title("Kto z kim się najczęściej zgadza")
plt.ylabel("Procent tweetów")
plt.xticks(rotation=15, ha="right")
plt.tight_layout()
plt.show()

# 4. Macierze pomyłek (crosstab) – które klasy się mylą między modelami
print("\nMacierz LLM vs FinBERT (udział w wierszu):")
print(pd.crosstab(
    sent_df["llm_sent_tweet"], sent_df["fin_sent_tweet"],
    normalize="index"
).round(2))

print("\nMacierz LLM vs RoBERTa (udział w wierszu):")
print(pd.crosstab(
    sent_df["llm_sent_tweet"], sent_df["rob_sent_tweet"],
    normalize="index"
).round(2))

print("\nMacierz FinBERT vs RoBERTa (udział w wierszu):")
print(pd.crosstab(
    sent_df["fin_sent_tweet"], sent_df["rob_sent_tweet"],
    normalize="index"
).round(2))

import matplotlib.pyplot as plt
import numpy as np

# 1. Rozkłady klas sentymentu dla LLM, FinBERT i RoBERTa
# --------------------------------------------------------------------
def plot_sentiment_distributions(llm_dist, fin_dist, rob_dist):
    """
    llm_dist, fin_dist, rob_dist : pandas.Series
        Index: nazwy klas (np. ['negative', 'neutral', 'positive'])
        Values: udziały w % (mogą być floaty typu 50.36 itd.)
    """
    models = [
        ("LLM", llm_dist),
        ("FinBERT", fin_dist),
        ("RoBERTa", rob_dist),
    ]

    fig, axes = plt.subplots(1, 3, figsize=(12, 4), sharey=True)

    for ax, (name, s) in zip(axes, models):
        # upewnij się, że kolejność jest sensowna (opcjonalne sortowanie po indeksie)
        s_sorted = s.sort_index()
        ax.bar(s_sorted.index, s_sorted.values)
        ax.set_title(name)
        ax.set_ylabel("Udział [%]")
        ax.set_ylim(0, 100)
        ax.set_xticklabels(s_sorted.index, rotation=45, ha="right")

    fig.tight_layout()
    plt.show()


# 2. Rozkład typów zgodności między modelami
# --------------------------------------------------------------------
def plot_agreement_distribution(agreement_series, as_percent=True):
    """
    agreement_series : pandas.Series
        Index: etykiety typu zgodności (np.
            ['wszyscy trzej', 'tylko LLM–FinBERT', ...])
        Values: liczności lub % (jeśli as_percent=False, policzymy % sami).
    as_percent : bool
        Jeśli True i suma != 100, wartości zostaną przeskalowane do %.
    """
    s = agreement_series.copy()

    if as_percent:
        if not np.isclose(s.sum(), 100.0):
            s = s / s.sum() * 100.0

    s_sorted = s.sort_values(ascending=False)

    fig, ax = plt.subplots(figsize=(7, 4))
    ax.bar(s_sorted.index, s_sorted.values)
    ax.set_ylabel("Udział [%]")
    ax.set_title("Rozkład typów zgodności modeli")
    ax.set_xticklabels(s_sorted.index, rotation=45, ha="right")
    ax.set_ylim(0, 100)

    # dodanie wartości nad słupkami (opcjonalne, ale ładne do pracy)
    for i, v in enumerate(s_sorted.values):
        ax.text(i, v + 1, f"{v:.1f}%", ha="center", va="bottom", fontsize=8)

    fig.tight_layout()
    plt.show()


# 3. Macierze pomyłek (heatmapy) dla par modeli
# --------------------------------------------------------------------
def plot_confusion_heatmap(cm_df, title):
    """
    cm_df : pandas.DataFrame
        Index: klasy modelu A (np. LLM)
        Columns: klasy modelu B (np. FinBERT)
        Values: udziały w wierszu (0–1)
    title : str
        Tytuł wykresu, np. "LLM vs FinBERT"
    """
    fig, ax = plt.subplots(figsize=(4, 4))

    # wartości 0–1 zamieniamy na %
    data = cm_df.values * 100.0
    im = ax.imshow(data, aspect="auto")

    # etykiety osi
    ax.set_xticks(np.arange(len(cm_df.columns)))
    ax.set_yticks(np.arange(len(cm_df.index)))
    ax.set_xticklabels(cm_df.columns, rotation=45, ha="right")
    ax.set_yticklabels(cm_df.index)

    ax.set_xlabel("Model B")
    ax.set_ylabel("Model A")
    ax.set_title(title)

    # liczby w komórkach
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            ax.text(
                j, i, f"{data[i, j]:.0f}%",
                ha="center", va="center", fontsize=8
            )

    fig.colorbar(im, ax=ax, label="Udział [%]")
    fig.tight_layout()
    plt.show()


def plot_all_confusion_matrices(cm_llm_fin, cm_llm_rob, cm_fin_rob):
    """
    cm_llm_fin, cm_llm_rob, cm_fin_rob : pandas.DataFrame
        Macierze pomyłek z udziałami w wierszu (0–1).
    """
    plot_confusion_heatmap(cm_llm_fin, "LLM vs FinBERT")
    plot_confusion_heatmap(cm_llm_rob, "LLM vs RoBERTa")
    plot_confusion_heatmap(cm_fin_rob, "FinBERT vs RoBERTa")

# 1. Rozkłady klas – wstaw swoje Series zamiast przykładowych nazw
# np. jeśli masz:
# llm_class_dist, finbert_class_dist, roberta_class_dist
plot_sentiment_distributions(llm_class_dist, finbert_class_dist, roberta_class_dist)

# 2. Rozkład typów zgodności – np. agreement_percent
plot_agreement_distribution(agreement_percent, as_percent=True)

# 3. Macierze pomyłek – np.
# cm_llm_fin, cm_llm_rob, cm_fin_rob
plot_all_confusion_matrices(cm_llm_fin, cm_llm_rob, cm_fin_rob)

# 6. (opcjonalnie) zapis do nowego pliku parquet z dodatkowymi kolumnami
OUT_PATH = "/content/drive/MyDrive/THESIS/combined_top_with_llm_fin_rob.parquet"
llm_df.to_parquet(OUT_PATH, index=False)
print("Zapisano zaktualizowany DataFrame do:", OUT_PATH)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# Założenie: masz DataFrame sent_df z kolumnami:
# 'llm_sent_tweet', 'fin_sent_tweet', 'rob_sent_tweet'
# (sent_df jest już dostępne z poprzednich kroków)
# ------------------------------------------------------------

# Bierzemy tylko tweety, które mają etykiety od wszystkich trzech modeli
# sent_df już zawiera tylko wiersze z niepustymi wartościami dla tych kolumn
df_common = sent_df.copy()

print("Liczba tweetów z oceną wszystkich trzech modeli:", len(df_common))

# ============================================
# 1. Rozkłady klas sentymentu dla trzech modeli
# ============================================

llm_class_dist = df_common['llm_sent_tweet'].value_counts(normalize=True) * 100
finbert_class_dist = df_common['fin_sent_tweet'].value_counts(normalize=True) * 100
roberta_class_dist = df_common['rob_sent_tweet'].value_counts(normalize=True) * 100

print("\nRozkład klas dla LLM (w %):")
print(llm_class_dist.sort_index())

print("\nRozkład klas dla FinBERT (w %):")
print(finbert_class_dist.sort_index())

print("\nRozkład klas dla RoBERTa (w %):")
print(roberta_class_dist.sort_index())

# Funkcja do narysowania trzech słupków obok siebie
def plot_sentiment_distributions(llm_dist, fin_dist, rob_dist):
    models = [
        ("LLM", llm_dist),
        ("FinBERT", fin_dist),
        ("RoBERTa", rob_dist),
    ]

    fig, axes = plt.subplots(1, 3, figsize=(12, 4), sharey=True)

    for ax, (name, s) in zip(axes, models):
        s_sorted = s.sort_index()
        ax.bar(s_sorted.index, s_sorted.values)
        ax.set_title(name)
        ax.set_ylabel("Udział [%]")
        ax.set_ylim(0, 100)
        ax.set_xticklabels(s_sorted.index, rotation=45, ha="right")

    fig.tight_layout()
    plt.show()

plot_sentiment_distributions(llm_class_dist, finbert_class_dist, roberta_class_dist)

# ============================================
# 2. Rozkład typów zgodności między modelami
# ============================================

def classify_agreement(row):
    l = row['llm_sent_tweet']
    f = row['fin_sent_tweet']
    r = row['rob_sent_tweet']

    all_equal = (l == f == r)
    lf = (l == f) and not all_equal
    lr = (l == r) and not all_equal
    fr = (f == r) and not all_equal

    if all_equal:
        return "wszyscy trzej"
    elif lf and not (lr or fr):
        return "tylko LLM–FinBERT"
    elif lr and not (lf or fr):
        return "tylko LLM–RoBERTa"
    elif fr and not (lf or lr):
        return "tylko FinBERT–RoBERTa"
    # If none of the pairwise agreements are exclusive or all agree, check if no agreement at all.
    # This covers cases where two agree, but not exclusively, or none agree.
    # The previous logic in GPMLRjSsvyAl for `none_agree` already handles this correctly,
    # but we need to ensure this function reflects it for cases not covered by the `if/elif` above
    # For this specific function, we prioritize specific types of agreement.
    # If no specific type of agreement matches the defined conditions,
    # it falls into 'brak zgodności'.
    else:
        return "brak zgodności"

df_common['agreement_type'] = df_common.apply(classify_agreement, axis=1)

agreement_counts = df_common['agreement_type'].value_counts()
agreement_percent = df_common['agreement_type'].value_counts(normalize=True) * 100

print("\nRozkład typów zgodności (liczby):")
print(agreement_counts)

print("\nRozkład typów zgodności (w %):")
print(agreement_percent)

def plot_agreement_distribution(agreement_series):
    s = agreement_series.copy()
    # jeśli nie jest dokładnie 100, przeskaluj do %
    if not np.isclose(s.sum(), 100.0):
        s = s / s.sum() * 100.0

    s_sorted = s.sort_values(ascending=False)

    fig, ax = plt.subplots(figsize=(7, 4))
    ax.bar(s_sorted.index, s_sorted.values)
    ax.set_ylabel("Udział [%]")
    ax.set_title("Rozkład typów zgodności modeli")
    ax.set_xticklabels(s_sorted.index, rotation=45, ha="right")
    ax.set_ylim(0, 100)

    # wartości nad słupkami
    for i, v in enumerate(s_sorted.values):
        ax.text(i, v + 1, f"{v:.1f}%",
                ha="center", va="bottom", fontsize=8)

    fig.tight_layout()
    plt.show()

plot_agreement_distribution(agreement_percent)

# ============================================
# 3. Macierze pomyłek (heatmapy) dla par modeli
# ============================================

def confusion_row_normalized(df_cm, col_true, col_pred):
    """
    Zwraca macierz pomyłek (DataFrame) znormalizowaną w wierszach (0–1).
    wiersz = etykieta modelu "true", kolumna = etykieta modelu "pred".
    """
    cm = (
        df_cm
        .groupby([col_true, col_pred])
        .size()
        .unstack(fill_value=0)
        .astype(float)
    )
    cm = cm.div(cm.sum(axis=1), axis=0)  # normalizacja wierszami
    return cm

cm_llm_fin = confusion_row_normalized(df_common, 'llm_sent_tweet', 'fin_sent_tweet')
cm_llm_rob = confusion_row_normalized(df_common, 'llm_sent_tweet', 'rob_sent_tweet')
cm_fin_rob = confusion_row_normalized(df_common, 'fin_sent_tweet', 'rob_sent_tweet')

print("\nMacierz LLM vs FinBERT (udział w wierszu):")
print(cm_llm_fin)

print("\nMacierz LLM vs RoBERTa (udział w wierszu):")
print(cm_llm_rob)

print("\nMacierz FinBERT vs RoBERTa (udział w wierszu):")
print(cm_fin_rob)

def plot_confusion_heatmap(cm_df, title):
    fig, ax = plt.subplots(figsize=(4, 4))

    data = cm_df.values * 100.0  # na %
    im = ax.imshow(data, aspect="auto")

    ax.set_xticks(np.arange(len(cm_df.columns)))
    ax.set_yticks(np.arange(len(cm_df.index)))
    ax.set_xticklabels(cm_df.columns, rotation=45, ha="right")
    ax.set_yticklabels(cm_df.index)

    ax.set_xlabel("Model B")
    ax.set_ylabel("Model A")
    ax.set_title(title)

    # liczby w komórkach
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            ax.text(j, i, f"{data[i, j]:.0f}%",
                    ha="center", va="center", fontsize=8)

    fig.colorbar(im, ax=ax, label="Udział [%]")
    fig.tight_layout()
    plt.show()

plot_confusion_heatmap(cm_llm_fin, "LLM vs FinBERT")
plot_confusion_heatmap(cm_llm_rob, "LLM vs RoBERTa")
plot_confusion_heatmap(cm_fin_rob, "FinBERT vs RoBERTa")

