# -*- coding: utf-8 -*-
"""trenowanie_30p_25/11/2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LL45VM1xWEdv38QF4PH_-YJ6HL58UxC7
"""

!pip install -q transformers datasets accelerate evaluate xgboost

import pandas as pd
import numpy as np
import torch
from sklearn.metrics import classification_report, confusion_matrix
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModel,
    Trainer,
    TrainingArguments,
)
import evaluate

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

from google.colab import drive
drive.mount('/content/drive')

DATA_PATH = '/content/drive/MyDrive/THESIS/combined_top_with_llm_final.parquet'

df = pd.read_parquet(DATA_PATH)
print(df.shape)
print(df.columns)

display(df[['clean_text','created_at_local','year','month',
            'llm_about_tsla','tesla_keywords_found',
            'llm_sent_tweet','llm_sent_quote','llm_stance',
            'llm_impact','llm_sarcasm','llm_conf']].head())

# # Filtrowanie tylko do tweetów, które LLM uznał za związane z Teslą
# df_tsla = df[df['llm_about_tsla'] == True].copy()
# print("Po filtrze llm_about_tsla == True:", df_tsla.shape)

# Podział czasowy
train_df = df[(df['year'] < 2024) | ((df['year'] == 2024) & (df['month'] <= 5))].copy()
val_df   = df[(df['year'] == 2024) & (df['month'] >= 6) & (df['month'] <= 11)].copy()
test_df  = df[(df['year'] == 2025) | ((df['year'] == 2024) & (df['month'] >= 12))].copy()

for name, part in [('train', train_df), ('val', val_df), ('test', test_df)]:
    print(name, part.shape)

total_rows = len(train_df) + len(val_df) + len(test_df)
print(f"train: {len(train_df)/total_rows*100:.2f}%")
print(f"val:   {len(val_df)/total_rows*100:.2f}%")
print(f"test:  {len(test_df)/total_rows*100:.2f}%")

TARGET_COL = 'avg1_3'
print("Opis statystyczny avg1_3(train):")
print(train_df[TARGET_COL].describe())
print(train_df[TARGET_COL].quantile([0.1,0.25,0.5,0.75,0.9]))

threshold = 0.15  # Twoje założenie

def label_from_return(x, th=threshold):
    if x > th:
        return "up"
    elif x < -th:
        return "down"
    else:
        return "neutral"

for d in (train_df, val_df, test_df):
    d['label_str'] = d[TARGET_COL].apply(label_from_return)

print("Train label counts:")
print(train_df['label_str'].value_counts())
print("\nVal label counts:")
print(val_df['label_str'].value_counts())
print("\nTest label counts:")
print(test_df['label_str'].value_counts())

import ast # Add this line to import the ast module

# mapowania "ręczne"
sent_map   = {'negative': -1, 'neutral': 0, 'positive': 1}
stance_map = {'bearish': -1, 'unclear': 0, 'bullish': 1}
impact_map = {'none': 0, 'low': 1, 'medium': 2, 'high': 3}

def add_llm_numeric_cols(df_part):
    df_part = df_part.copy()
    df_part['llm_sent_tweet_num']  = df_part['llm_sent_tweet'].map(sent_map).fillna(0)
    df_part['llm_sent_quote_num']  = df_part['llm_sent_quote'].map(sent_map).fillna(0)
    df_part['llm_stance_num']      = df_part['llm_stance'].map(stance_map).fillna(0)
    df_part['llm_impact_num']      = df_part['llm_impact'].map(impact_map).fillna(0)
    df_part['llm_sarcasm_num']     = df_part['llm_sarcasm'].astype(int)
    df_part['llm_conf_num']        = df_part['llm_conf'].astype(float)
    # Fix for tesla_keywords_found: Convert string representation of list to actual list,
    # then check if the list is non-empty.
    df_part['tesla_keywords_num'] = df_part['tesla_keywords_found'].apply(
        lambda x: 1 if (isinstance(x, str) and x.strip() and ast.literal_eval(x)) else 0
    )
    return df_part

train_df = add_llm_numeric_cols(train_df)
val_df   = add_llm_numeric_cols(val_df)
test_df  = add_llm_numeric_cols(test_df)

llm_feature_cols = [
    'llm_sent_tweet_num',
    'llm_sent_quote_num',
    'llm_stance_num',
    'llm_impact_num',
    'llm_sarcasm_num',
    'llm_conf_num',
    'tesla_keywords_num',
]

display(train_df[['clean_text','label_str'] + llm_feature_cols].head(500))

print('--- Verifying llm_sent_tweet mapping ---')
print(train_df[['llm_sent_tweet', 'llm_sent_tweet_num']].drop_duplicates().sort_values(by='llm_sent_tweet_num'))

print('\n--- Verifying llm_sent_quote mapping ---')
print(train_df[['llm_sent_quote', 'llm_sent_quote_num']].drop_duplicates().sort_values(by='llm_sent_quote_num'))

print('\n--- Verifying llm_stance mapping ---')
print(train_df[['llm_stance', 'llm_stance_num']].drop_duplicates().sort_values(by='llm_stance_num'))

print('\n--- Verifying llm_impact mapping ---')
print(train_df[['llm_impact', 'llm_impact_num']].drop_duplicates().sort_values(by='llm_impact_num'))

print('\n--- Verifying llm_sarcasm mapping ---')
print(train_df[['llm_sarcasm', 'llm_sarcasm_num']].drop_duplicates().sort_values(by='llm_sarcasm_num'))

print('\n--- Verifying tesla_keywords_found mapping ---')
# For tesla_keywords_found, check counts of original vs. new column
print('Original tesla_keywords_found counts:')
print(train_df['tesla_keywords_found'].apply(lambda x: bool(ast.literal_eval(x)) if isinstance(x, str) and x.strip() else False).value_counts())
print('Mapped tesla_keywords_num counts:')
print(train_df['tesla_keywords_num'].value_counts())

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(train_df['label_str'])

def encode_labels(df_part):
    df_part = df_part.copy()
    df_part['label'] = label_encoder.transform(df_part['label_str'])
    return df_part

train_df = encode_labels(train_df)
val_df   = encode_labels(val_df)
test_df  = encode_labels(test_df)

print("Mapowanie klas:", dict(enumerate(label_encoder.classes_)))

cols_for_hf = ['clean_text', 'label'] + llm_feature_cols

hf_train = Dataset.from_pandas(train_df[cols_for_hf])
hf_val   = Dataset.from_pandas(val_df[cols_for_hf])
hf_test  = Dataset.from_pandas(test_df[cols_for_hf])

dataset = DatasetDict({
    "train": hf_train,
    "validation": hf_val,
    "test": hf_test,
})

print(dataset)

from transformers import AutoTokenizer

MODEL_NAME = "ProsusAI/finbert"  # FinBERT jako baza

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def preprocess_function(examples):
    # Ensure clean_text elements are strings
    texts = [str(text) if text is not None else "" for text in examples["clean_text"]]
    enc = tokenizer(
        texts,
        truncation=True,
        max_length=128,
        padding=False,
    )
    # Dodatkowe cechy przekazujemy dalej 1:1
    for col in llm_feature_cols:
        enc[col] = examples[col]
    enc["labels"] = examples["label"]
    return enc

tokenized_datasets = dataset.map(preprocess_function, batched=True)
# Modified: Only remove 'clean_text' and 'label', keep llm_feature_cols
tokenized_datasets = tokenized_datasets.remove_columns(["clean_text", "label"])
print(tokenized_datasets)

import torch.nn as nn
from transformers import AutoModel, PreTrainedModel
from transformers.modeling_outputs import SequenceClassifierOutput

class FinBertWithFeatures(PreTrainedModel):
    config_class = AutoModel.from_pretrained(MODEL_NAME, attn_implementation="eager").config.__class__

    def __init__(self, config, num_extra_features, num_labels):
        super().__init__(config)
        self.num_labels = num_labels
        self.bert = AutoModel.from_pretrained(MODEL_NAME, config=config, attn_implementation="eager")
        self.dropout = nn.Dropout(0.1)
        self.classifier = nn.Linear(config.hidden_size + num_extra_features, num_labels)

        self.init_weights()

    def forward(
        self,
        input_ids=None,
        attention_mask=None,
        labels=None,
        llm_sent_tweet_num=None,
        llm_sent_quote_num=None,
        llm_stance_num=None,
        llm_impact_num=None,
        llm_sarcasm_num=None,
        llm_conf_num=None,
        tesla_keywords_num=None,
        **kwargs
    ):
        outputs = self.bert(
            input_ids=input_ids,
            attention_mask=attention_mask,
        )
        # cls embedding
        if hasattr(outputs, "pooler_output") and outputs.pooler_output is not None:
            pooled = outputs.pooler_output
        else:
            pooled = outputs.last_hidden_state[:, 0]

        # zlepienie cech numerycznych
        extra_feats_list = [
            llm_sent_tweet_num,
            llm_sent_quote_num,
            llm_stance_num,
            llm_impact_num,
            llm_sarcasm_num,
            llm_conf_num,
            tesla_keywords_num,
        ]
        extra_feats = torch.stack(extra_feats_list, dim=1).float()

        x = torch.cat([pooled, extra_feats], dim=1)
        x = self.dropout(x)
        logits = self.classifier(x)

        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss()
            loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))

        return SequenceClassifierOutput(
            loss=loss,
            logits=logits,
        )

num_extra_features = len(llm_feature_cols)
num_labels = len(label_encoder.classes_)

base_config = AutoModel.from_pretrained(MODEL_NAME, attn_implementation="eager").config
model = FinBertWithFeatures(base_config, num_extra_features=num_extra_features, num_labels=num_labels)
model.to(device)

from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

accuracy_metric = evaluate.load("accuracy")
f1_metric = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    acc = accuracy_metric.compute(predictions=preds, references=labels)["accuracy"]
    f1_macro = f1_metric.compute(predictions=preds, references=labels, average="macro")["f1"]
    return {"accuracy": acc, "f1_macro": f1_macro}

training_args = TrainingArguments(
    output_dir="/content/finbert_tsla_movement",
    num_train_epochs=5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    logging_steps=10,
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

import transformers
print(f"Transformers version: {transformers.__version__}")

print(f"evaluation_strategy: {training_args.eval_strategy}")
print(f"load_best_model_at_end: {training_args.load_best_model_at_end}")
print(f"metric_for_best_model: {training_args.metric_for_best_model}")

trainer.train()

print("\n=== EVAL: validation ===")
val_results = trainer.evaluate(tokenized_datasets["validation"])
print(val_results)

print("\n=== EVAL: test ===")
test_results = trainer.evaluate(tokenized_datasets["test"])
print(test_results)

# Raport z klasyfikacją na teście
pred_output = trainer.predict(tokenized_datasets["test"])
logits = pred_output.predictions
y_pred = np.argmax(logits, axis=-1)
y_true = np.array(test_df['label'])

print("\n=== Classification report (TEST) ===")
print(classification_report(y_true, y_pred, target_names=label_encoder.classes_))

print("\nConfusion matrix (TEST):")
print(confusion_matrix(y_true, y_pred))

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# User provided confusion matrix values
cm_values = np.array([
    [ 8, 63,  5],
    [ 3, 30,  4],
    [ 3, 45,  7]
])

# Define labels directly as label_encoder is not in scope
labels = ['down', 'neutral', 'up']

plt.figure(figsize=(8, 6))
sns.heatmap(cm_values, annot=True, fmt="d", cmap="Blues", xticklabels=labels, yticklabels=labels)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (TEST Set)')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# =====================================================
# Dane z Twojego raportu (TEST)
# =====================================================

class_names = ["down", "neutral", "up"]

# macierz pomyłek: wiersze = klasa prawdziwa, kolumny = klasa przewidziana
cm = np.array([
    [8, 63, 5],   # true: down
    [3, 30, 4],   # true: neutral
    [3, 45, 7]    # true: up
])

# sprawdzenie sum wierszy = support (76, 37, 55)
row_sums = cm.sum(axis=1, keepdims=True).astype(float)
print("Support (z wierszy macierzy):", row_sums.flatten().astype(int))

# =====================================================
# Ułamkowa macierz: udział w wierszu (0–1)
# =====================================================

cm_frac = cm / row_sums  # każdy wiersz dzielony przez sumę wiersza

print("\nMacierz pomyłek znormalizowana w wierszach (ułamki):")
for i, cls in enumerate(class_names):
    row_str = ", ".join(
        f"{class_names[j]}={cm_frac[i, j]:.2f}"
        for j in range(len(class_names))
    )
    print(f"true {cls}: {row_str}")

# =====================================================
# Recall per klasa (diagonał z cm_frac)
# =====================================================

recall_per_class = np.diag(cm_frac)

print("\nRecall dla każdej klasy (z macierzy):")
for cls, r in zip(class_names, recall_per_class):
    print(f"{cls}: {r:.2f}")

# =====================================================
# Wykres macierzy w ułamkach (heatmapa)
# =====================================================

fig, ax = plt.subplots(figsize=(5, 4))

im = ax.imshow(cm_frac, aspect="auto")  # wartości 0–1

# Oś X/Y
ax.set_xticks(np.arange(len(class_names)))
ax.set_yticks(np.arange(len(class_names)))
ax.set_xticklabels(class_names)
ax.set_yticklabels(class_names)

ax.set_xlabel("Klasa przewidziana")
ax.set_ylabel("Klasa prawdziwa")
ax.set_title("Macierz pomyłek FinBERT")

# Wpisanie wartości w komórkach: ułamek + liczba
for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        frac = cm_frac[i, j]
        ax.text(
            j, i,
            f"{frac:.2f}",
            ha="center",
            fontsize=8
        )

fig.colorbar(im, ax=ax, label="Udział (0–1)")
fig.tight_layout()
plt.show()

TRADE_MINUTES = 3
RET_COL = f"after_{TRADE_MINUTES}m"

# tworzymy DataFrame z predykcjami
test_pred_df = test_df.copy()
test_pred_df['pred_label_id'] = y_pred
test_pred_df['pred_label_str'] = label_encoder.inverse_transform(y_pred)

def trade_decision(pred_label_str):
    if pred_label_str == "up":
        return "buy"
    elif pred_label_str == "down":
        return "sell"
    else:
        return "hold"

test_pred_df['trade_decision'] = test_pred_df['pred_label_str'].apply(trade_decision)

def pnl_from_decision(row):
    decision = row['trade_decision']
    if RET_COL not in row or pd.isna(row[RET_COL]):
        return 0.0
    ret = row[RET_COL]  # np. zmiana % vs open

    if decision == "buy":
        return ret
    elif decision == "sell":
        return -ret
    else:
        return 0.0

test_pred_df['pnl_model'] = test_pred_df.apply(pnl_from_decision, axis=1)

# Możesz też liczyć PnL tylko na realnych up/down (bez neutralnych prawdziwych):
mask_tradeable = test_pred_df['label_str'].isin(['up','down'])
print("Liczba tweetów tradeable (real up/down):", mask_tradeable.sum())
print("Średni PnL na tradeable:", test_pred_df.loc[mask_tradeable, 'pnl_model'].mean())
print("Suma PnL na tradeable:", test_pred_df.loc[mask_tradeable, 'pnl_model'].sum())

# Zapisz predykcje do pliku na Drive
OUT_TEST_PATH = '/content/drive/MyDrive/THESIS/finbert_test_predictions_3m.csv'
test_pred_df.to_csv(OUT_TEST_PATH, index=False)
print("Zapisano predykcje test do:", OUT_TEST_PATH)