# -*- coding: utf-8 -*-
"""XGB_11.12.2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ntDV5LUiibg8mieJeWnccIPNFynzIyWm
"""

from google.colab import drive
drive.mount('/content/drive')

# -*- coding: utf-8 -*-

!pip install -q transformers accelerate xgboost

import pandas as pd
import numpy as np
import torch
import xgboost as xgb
import matplotlib.pyplot as plt
import seaborn as sns

from transformers import AutoTokenizer, AutoModel
from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight

# ============================================================
# CONFIG
# ============================================================
DATA_PATH = "/content/drive/MyDrive/THESIS/combined_top_with_llm_final.parquet"
MODEL_NAME = "ProsusAI/finbert"
SEED = 42
NEUTRAL_RANGE = 0.60
PENALTY_MULTIPLIER = 5.0  # Mnożnik agresywności dla klas UP/DOWN

# ============================================================
# 1. LOAD DATA
# ============================================================
from google.colab import drive
drive.mount('/content/drive')

def parse_date(s):
    if pd.isna(s): return pd.NaT
    s = str(s).replace(" CEST", "+0200").replace(" CET", "+0100")
    return pd.to_datetime(s, utc=True, format="mixed")

df = pd.read_parquet(DATA_PATH)
df["createdAt"] = df["created_at_local"].apply(parse_date)
df = df.dropna(subset=["createdAt"]).sort_values("createdAt").reset_index(drop=True)

print(f"Wczytano {len(df)} wierszy. Zakres dat: {df['createdAt'].min()} do {df['createdAt'].max()}")

# ============================================================
# 2. FEATURE ENGINEERING (MARKET + LLM)
# ============================================================
sent_map = {"negative": -1, "neutral": 0, "positive": 1}
impact_map = {"none": 0, "low": 1, "medium": 2, "high": 3}

df["llm_sent_num"] = df["llm_sent_tweet"].map(sent_map).fillna(0)
df["llm_impact_num"] = df["llm_impact"].map(impact_map).fillna(0)
df["llm_conf_num"] = pd.to_numeric(df["llm_conf"], errors="coerce").fillna(0.5)

# Cechy rynkowe (Market Features)
vol_cols = ["before_1m", "before_3m", "before_5m"]
df["market_volatility"] = df[vol_cols].std(axis=1).fillna(0)
df["market_momentum"] = df["before_5m"].fillna(0)

df["signal_strength"] = (
    df["llm_sent_num"] * df["llm_conf_num"] * df["llm_impact_num"]
)

feature_cols = [
    "llm_sent_num",
    "llm_impact_num",
    "market_volatility",
    "market_momentum",
    "signal_strength",
]

# ============================================================
# 3. BEZPIECZNY LABELING (NO DATA LEAKAGE)
# ============================================================
# FIX: Obliczamy progi TYLKO na historycznej części danych (np. pierwsze 60%)
# Reszta (ostatnie 40%) to "przyszłość", którą będziemy testować.

calibration_idx = int(len(df) * 0.60)
calibration_data = df["avg1_3"].iloc[:calibration_idx].dropna()

q_low = (1 - NEUTRAL_RANGE) / 2
q_high = 1 - q_low

# Te progi są ustalone raz na podstawie przeszłości i stosowane do przyszłości
th_down = calibration_data.quantile(q_low)
th_up = calibration_data.quantile(q_high)

print(f"\n=== PARAMETRY LABELINGU (Na podst. pierwszych {calibration_idx} próbek) ===")
print(f"Próg DOWN (<): {th_down:.5f}")
print(f"Próg UP (>):   {th_up:.5f}")

def labelize(x):
    if x <= th_down: return "down"
    if x >= th_up: return "up"
    return "neutral"

df["label_str"] = df["avg1_3"].apply(labelize)

# Encoder
le = LabelEncoder()
# Fitujemy na wszystkich możliwych klasach (żeby zachować kolejność ID),
# to nie jest wyciek, bo znamy nazwy klas z góry.
le.fit(["down", "neutral", "up"])
df["label"] = le.transform(df["label_str"])

print("\nRozkład klas w całym zbiorze (wynikowy):")
print(df["label_str"].value_counts(normalize=True))

# ============================================================
# 4. FINBERT EMBEDDINGS
# ============================================================
def get_embeddings(texts, batch=32):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Generowanie embeddingów na urządzeniu: {device}...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = AutoModel.from_pretrained(MODEL_NAME).to(device)

    out = []
    texts = list(texts)
    model.eval()

    # Batch processing
    for i in range(0, len(texts), batch):
        if i % 1000 == 0 and i > 0: print(f"Przetworzono {i}/{len(texts)}")
        t = texts[i : i + batch]
        inp = tokenizer(
            t, padding=True, truncation=True, max_length=64, return_tensors="pt"
        ).to(device)

        with torch.no_grad():
            emb = model(**inp).last_hidden_state[:, 0, :].cpu().numpy()
        out.append(emb)

    return np.vstack(out)

# Generujemy embeddingi (może chwilę potrwać)
X_text = get_embeddings(df["clean_text"].astype(str))
X_feat = df[feature_cols].values

# Łączymy cechy
X = np.concatenate([X_text, X_feat], axis=1)
y = df["label"].values

print("\nShape X:", X.shape)
print("Shape y:", y.shape)

# ============================================================
# 5. TIME-SERIES SPLIT Z POPRAWNYM WAŻENIEM I ZAPISEM DANYCH
# ============================================================
tscv = TimeSeriesSplit(n_splits=5)

# Indeksy klas do manipulacji wagami
try:
    up_idx = le.transform(['up'])[0]
    down_idx = le.transform(['down'])[0]
    neutral_idx = le.transform(['neutral'])[0]
except:
    print("UWAGA: Brakuje którejś klasy w encoderze.")

acc_per_fold = []
last_pred = None
last_test = None
last_test_df = None  # <--- NOWE: Tutaj przechowamy wiersze DF dla ostatniego testu

print("\n=== ROZPOCZYNAMY TRENING (Walk-Forward Validation) ===")

for fold, (train_idx, test_idx) in enumerate(tscv.split(X)):
    print(f"\n>>> FOLD {fold+1} <<<")

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    classes_in_train = np.unique(y_train)
    weights = compute_class_weight("balanced", classes=classes_in_train, y=y_train)
    weight_dict = dict(zip(classes_in_train, weights))

    # Penalty Multiplier
    if up_idx in weight_dict:
        weight_dict[up_idx] *= PENALTY_MULTIPLIER
    if down_idx in weight_dict:
        weight_dict[down_idx] *= PENALTY_MULTIPLIER

    sample_w = np.array([weight_dict[c] for c in y_train])

    # --------------------------------------------------------
    # Model XGBoost
    # --------------------------------------------------------
    model = xgb.XGBClassifier(
        n_estimators=400,
        max_depth=6,
        learning_rate=0.02,
        subsample=0.8,
        colsample_bytree=0.6,
        max_delta_step=1,
        objective="multi:softmax",
        num_class=len(le.classes_),
        random_state=SEED,
        n_jobs=-1,
    )

    model.fit(X_train, y_train, sample_weight=sample_w)

    y_pred = model.predict(X_test)

    print(classification_report(y_test, y_pred, target_names=le.classes_, zero_division=0))

    # Zapisujemy wyniki TYLKO dla ostatniego folda (najświeższe dane)
    if fold == 4:
        last_pred = y_pred
        last_test = y_test
        # Zapisujemy wycinek oryginalnego DataFrame, żeby mieć dostęp do zwrotów (avg1_3)
        last_test_df = df.iloc[test_idx].copy()

# ============================================================
# 6. WIZUALIZACJA WYNIKÓW (OSTATNI FOLD)
# ============================================================
if last_test is not None:
    cm = confusion_matrix(last_test, last_pred)
    cm_norm = cm.astype(float) / (cm.sum(axis=1)[:, np.newaxis] + 1e-9)

    plt.figure(figsize=(8, 6))
    sns.heatmap(
        cm_norm,
        annot=True,
        cmap="RdYlGn",
        xticklabels=le.classes_,
        yticklabels=le.classes_,
        fmt=".2f",
        vmin=0, vmax=1
    )
    plt.title(f"Macierz Pomyłek (Recall) - Test na najnowszych danych\nPenalty x{PENALTY_MULTIPLIER}")
    plt.ylabel("Prawda (True Label)")
    plt.xlabel("Predykcja (Predicted Label)")
    plt.show()

# ============================================================
# 7. SYMULACJA HANDLU (BACKTEST PnL)
# ============================================================
print("\n=== SYMULACJA HANDLU (BACKTEST) ===")

# Ustawienia symulacji
PNL_RET_COL = "avg1_3"  # Kolumna zwrotu, na której opieramy wynik (zgodnie z labelingiem)

# 1. Przypisanie predykcji do DataFrame
last_test_df['pred_label_id'] = last_pred
last_test_df['pred_label_str'] = le.inverse_transform(last_pred)

# 2. Funkcja decyzyjna (Mapowanie modelu na akcje)
def trade_decision(pred_label_str):
    if pred_label_str == "up":
        return "buy"
    elif pred_label_str == "down":
        return "sell"
    else:
        return "hold"

last_test_df['trade_decision'] = last_test_df['pred_label_str'].apply(trade_decision)

# 3. Obliczanie PnL
def pnl_from_decision(row):
    decision = row['trade_decision']

    # Sprawdzenie czy mamy dane o zwrocie
    if PNL_RET_COL not in row or pd.isna(row[PNL_RET_COL]):
        return 0.0

    ret = row[PNL_RET_COL]  # Zwrot w % (np. 0.0015 to 0.15%)

    if decision == "buy":
        return ret
    elif decision == "sell":
        return -ret  # Shortowanie: zarabiamy gdy cena spada
    else:
        return 0.0

last_test_df['pnl_model'] = last_test_df.apply(pnl_from_decision, axis=1)

# 4. Statystyki
mask_tradeable = last_test_df['trade_decision'].isin(['buy', 'sell'])
trades_count = mask_tradeable.sum()
total_pnl = last_test_df.loc[mask_tradeable, 'pnl_model'].sum()
mean_pnl = last_test_df.loc[mask_tradeable, 'pnl_model'].mean()

print(f"Liczba transakcji (Buy/Sell): {trades_count}")
print(f"Średni PnL na transakcję: {mean_pnl:.6f}")
print(f"Całkowity PnL (Suma): {total_pnl:.6f}")

# Wyświetlenie przykładowych wierszy z akcją
print("\nPrzykładowe transakcje:")
print(last_test_df[mask_tradeable][['createdAt', 'clean_text', 'avg1_3', 'pred_label_str', 'pnl_model']].head(10))

# ============================================================
# 8. PRZYGOTOWANIE I ZAPIS PLIKU (IDENTYCZNIE JAK FINBERT)
# ============================================================

# 1. Sprawdzamy, czy pętla treningowa się wykonała i mamy dane
if last_test_df is None or last_pred is None:
    raise ValueError("Błąd: Nie uruchomiono pętli treningowej (brak last_test_df)!")

# Tworzymy kopię roboczą
xgb_output = last_test_df.copy()

# 2. Dodajemy predykcje z modelu XGBoost
# (LabelEncoder 'le' musi być tym samym, który był użyty w treningu)
xgb_output['pred_label_id'] = last_pred
xgb_output['pred_label_str'] = le.inverse_transform(last_pred)

# 3. Logika handlowa (Decyzja) - Kopia logiki z pliku FinBERT
def trade_decision_func(pred_str):
    if pred_str == "up":
        return "buy"
    elif pred_str == "down":
        return "sell"
    else:
        return "hold"

xgb_output['trade_decision'] = xgb_output['pred_label_str'].apply(trade_decision_func)

# 4. Logika PnL (Zysk/Strata) - Kopia logiki z pliku FinBERT
# FinBERT używa kolumny 'after_3m' (zdefiniowanej jako RET_COL).
# Ponieważ oba skrypty korzystają z tego samego pliku .parquet, ta kolumna tu jest.
RET_COL = "after_3m"

if RET_COL not in xgb_output.columns:
    print(f"UWAGA: Brak kolumny {RET_COL}, używam avg1_3 jako zamiennika (wyniki mogą się różnić).")
    RET_COL = "avg1_3"

def pnl_func(row):
    decision = row['trade_decision']

    if RET_COL not in row or pd.isna(row[RET_COL]):
        return 0.0

    ret = row[RET_COL] # Zmiana procentowa

    if decision == "buy":
        return ret
    elif decision == "sell":
        return -ret
    else:
        return 0.0

xgb_output['pnl_model'] = xgb_output.apply(pnl_func, axis=1)

# 5. Lista kolumn do zapisu (Format dla GUI)
cols_to_save = [
    "tweet_id", "text", "isQuote", "combined_quote_info", "isRetweet", "mentioned", "hashtags",
    "tesla_keywords_found", "clean_text", "created_at_local",
    "before_10m", "before_9m", "before_8m", "before_7m", "before_6m",
    "before_5m", "before_4m", "before_3m", "before_2m", "before_1m",
    "price_at_tweet_open",
    "after_1m", "after_2m", "after_3m", "after_4m", "after_5m",
    "after_6m", "after_7m", "after_8m", "after_9m", "after_10m",
    "after_11m", "after_12m", "after_13m", "after_14m", "after_15m",
    "after_16m", "after_17m", "after_18m", "after_19m", "after_20m", "after_30m",
    "avg1_3", "stability_before_3m", "stability_before_4m", "avg1_2", "avg1_4", "avg1_5",
    "tweet_year",
    "llm_about_tsla", "llm_sent_tweet", "llm_sent_quote", "llm_stance",
    "llm_impact", "llm_drivers", "llm_sarcasm", "llm_conf", "llm_rationale",
    "year", "month", "label_str",
    "llm_sent_tweet_num", "llm_sent_quote_num", "llm_stance_num", "llm_impact_num",
    "llm_sarcasm_num", "llm_conf_num", "tesla_keywords_num",
    "label", "pred_label_id", "pred_label_str", "trade_decision", "pnl_model"
]

# 6. Bezpieczny wybór kolumn i zapis
# Wybieramy tylko te kolumny, które faktycznie istnieją w danych (żeby uniknąć błędu)
final_cols = [c for c in cols_to_save if c in xgb_output.columns]

OUT_TEST_PATH = '/content/drive/MyDrive/THESIS/xgboost_backtest_results.csv'
xgb_output[final_cols].to_csv(OUT_TEST_PATH, index=False)

print("-" * 50)
print(f"SUKCES: Zapisano plik dla GUI: {OUT_TEST_PATH}")
print(f"Liczba wierszy: {len(xgb_output)}")
print(f"Suma PnL modelu (na podstawie {RET_COL}): {xgb_output['pnl_model'].sum():.4f}")
print("-" * 50)

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Assuming last_test, last_pred, and le are available from the previous execution
# If this cell is run independently, you might need to re-execute the training cell

# Get class names from the LabelEncoder
class_names = le.classes_

# Calculate the confusion matrix
cm = confusion_matrix(last_test, last_pred)

# Normalize the confusion matrix by rows (Recall)
# Add a small epsilon to avoid division by zero if a class has no true samples
cm_norm = cm.astype(float) / (cm.sum(axis=1, keepdims=True) + 1e-9)

print("Znormalizowana macierz pomyłek (udział w wierszu):")
for i, cls in enumerate(class_names):
    row_str = ", ".join(
        f"{class_names[j]}={cm_norm[i, j]:.2f}"
        for j in range(len(class_names))
    )
    print(f"true {cls}: {row_str}")

# Recall for each class (diagonal of the normalized matrix)
recall_per_class = np.diag(cm_norm)

print("\nRecall dla każdej klasy (z macierzy):")
for cls, r in zip(class_names, recall_per_class):
    print(f"{cls}: {r:.2f}")

# Plot the heatmap
plt.figure(figsize=(5, 4))
sns.heatmap(
    cm_norm,
    annot=True,
    cmap="viridis", # Changed colormap to viridis
    xticklabels=class_names,
    yticklabels=class_names,
    fmt=".2f",
    cbar_kws={'label': 'Udział (0-1)'} # Added colorbar label
)
plt.title("Macierz pomyłek XGB")
plt.ylabel("Klasa prawdziwa")
plt.xlabel("Klasa przewidziana")
plt.show()

# # ============================================================
# # 5. TIME-SERIES SPLIT Z POPRAWNYM WAŻENIEM
# # ============================================================
# tscv = TimeSeriesSplit(n_splits=5)

# # Indeksy klas do manipulacji wagami
# try:
#     up_idx = le.transform(['up'])[0]
#     down_idx = le.transform(['down'])[0]
#     neutral_idx = le.transform(['neutral'])[0]
# except:
#     print("UWAGA: Brakuje którejś klasy w encoderze.")

# acc_per_fold = []
# last_pred = None
# last_test = None

# print("\n=== ROZPOCZYNAMY TRENING (Walk-Forward Validation) ===")

# for fold, (train_idx, test_idx) in enumerate(tscv.split(X)):
#     print(f"\n>>> FOLD {fold+1} <<<")

#     X_train, X_test = X[train_idx], X[test_idx]
#     y_train, y_test = y[train_idx], y[test_idx]

#     classes_in_train = np.unique(y_train)
#     weights = compute_class_weight("balanced", classes=classes_in_train, y=y_train)
#     weight_dict = dict(zip(classes_in_train, weights))

#     # Penalty Multiplier
#     if up_idx in weight_dict:
#         weight_dict[up_idx] *= PENALTY_MULTIPLIER
#     if down_idx in weight_dict:
#         weight_dict[down_idx] *= PENALTY_MULTIPLIER

#     sample_w = np.array([weight_dict[c] for c in y_train])

#     print(f"Wagi klas w tym foldzie (po mnożniku x{PENALTY_MULTIPLIER}):")
#     for cls_val in classes_in_train:
#         cls_name = le.inverse_transform([cls_val])[0]
#         print(f"  {cls_name}: {weight_dict[cls_val]:.2f}")

#     # --------------------------------------------------------
#     # Model XGBoost
#     # --------------------------------------------------------
#     model = xgb.XGBClassifier(
#         n_estimators=400,
#         max_depth=6,
#         learning_rate=0.02,
#         subsample=0.8,
#         colsample_bytree=0.6,
#         max_delta_step=1,       # Stabilizacja przy wysokich wagach
#         objective="multi:softmax",
#         num_class=len(le.classes_),
#         random_state=SEED,
#         n_jobs=-1,
#     )

#     model.fit(X_train, y_train, sample_weight=sample_w)

#     y_pred = model.predict(X_test)

#     print(classification_report(y_test, y_pred, target_names=le.classes_, zero_division=0))

#     if fold == 4:
#         last_pred = y_pred
#         last_test = y_test

# # ============================================================
# # 6. WIZUALIZACJA WYNIKÓW (OSTATNI FOLD - NAJNOWSZE DANE)
# # ============================================================
# if last_test is not None:
#     cm = confusion_matrix(last_test, last_pred)
#     cm_norm = cm.astype(float) / (cm.sum(axis=1)[:, np.newaxis] + 1e-9)

#     plt.figure(figsize=(8, 6))
#     sns.heatmap(
#         cm_norm,
#         annot=True,
#         cmap="RdYlGn",
#         xticklabels=le.classes_,
#         yticklabels=le.classes_,
#         fmt=".2f",
#         vmin=0, vmax=1
#     )
#     plt.title(f"Macierz Pomyłek (Recall) - Test na najnowszych danych\nPenalty x{PENALTY_MULTIPLIER}")
#     plt.ylabel("Prawda (True Label)")
#     plt.xlabel("Predykcja (Predicted Label)")
#     plt.show()

#     print("\n--- Szczegółowe wyniki dla ostatniego okresu testowego ---")
#     print("Macierz pomyłek (ilościowo):")
#     print(cm)


#     df_res = pd.DataFrame({'true': last_test, 'pred': last_pred})
#     df_res['true_str'] = le.inverse_transform(df_res['true'])
#     df_res['pred_str'] = le.inverse_transform(df_res['pred'])

#     action_mask = df_res['pred_str'] != 'neutral'
#     if action_mask.sum() > 0:
#         correct_actions = (df_res.loc[action_mask, 'true'] == df_res.loc[action_mask, 'pred']).sum()
#         accuracy_on_action = correct_actions / action_mask.sum()
#         print(f"\nPrecyzja gdy model podejmuje akcję (Precision on Signal): {accuracy_on_action:.2%}")
#         print(f"Liczba podjętych akcji: {action_mask.sum()} / {len(df_res)}")
#     else:
#         print("\nModel nie podjął żadnej akcji (wszystko przewidział jako neutral).")